program dcMobile;

uses
  System.StartUpCopy,
  FMX.Forms,
  View.Login in 'View\View.Login.pas' {view_Login},
  DM.Main in 'DAO\DM.Main.pas' {DM_Main: TDataModule},
  Model.Usuarios in 'Model\Model.Usuarios.pas',
  Controller.Usuarios in 'Controller\Controller.Usuarios.pas',
  Common.Notificacao in 'Common\Common.Notificacao.pas',
  Common.Params in 'Common\Common.Params.pas',
  Model.RESTCadastro in 'Model\Model.RESTCadastro.pas',
  Controller.RESTCadastro in 'Controller\Controller.RESTCadastro.pas',
  View.Main in 'View\View.Main.pas' {view_Main},
  Model.RESTLogin in 'Model\Model.RESTLogin.pas',
  Controller.RESTLogin in 'Controller\Controller.RESTLogin.pas',
  View.Boletos in 'View\View.Boletos.pas' {view_Boletos},
  Model.RESTLancamentos in 'Model\Model.RESTLancamentos.pas',
  Controller.RESTLancamentos in 'Controller\Controller.RESTLancamentos.pas',
  Model.RESTPlanilhaCredito in 'Model\Model.RESTPlanilhaCredito.pas',
  Controller.RESTPlanilhaCredito in 'Controller\Controller.RESTPlanilhaCredito.pas',
  View.Cadastro in 'View\View.Cadastro.pas' {view_Cadastro},
  Model.RESTSuportTracking in 'Model\Model.RESTSuportTracking.pas',
  Controller.RESTSuportTracking in 'Controller\Controller.RESTSuportTracking.pas',
  View.BaixaBoletos in 'View\View.BaixaBoletos.pas' {view_BaixaBoletos},
  Model.RESTExtrato in 'Model\Model.RESTExtrato.pas',
  Controller.RESTExtratos in 'Controller\Controller.RESTExtratos.pas',
  Model.RESTEentregasDetalhe in 'Model\Model.RESTEentregasDetalhe.pas',
  Controller.RESTEntregasDetalhe in 'Controller\Controller.RESTEntregasDetalhe.pas',
  Model.RESTExtravios in 'Model\Model.RESTExtravios.pas',
  Controller.RESTExtravios in 'Controller\Controller.RESTExtravios.pas',
  Common.Utils in 'Common\Common.Utils.pas',
  View.Extratos2 in 'View\View.Extratos2.pas' {view_Extratos2},
  Model.RESTEentregas in 'Model\Model.RESTEentregas.pas',
  Controller.RESTEntregas in 'Controller\Controller.RESTEntregas.pas',
  View.EntregasDetalhe in 'View\View.EntregasDetalhe.pas' {view_EntregasDetalhe},
  Model.RESTEentregasDia in 'Model\Model.RESTEentregasDia.pas',
  Controller.RESTEntregasDia in 'Controller\Controller.RESTEntregasDia.pas',
  View.Extratos in 'View\View.Extratos.pas' {view_Extratos},
  View.EntregasDia in 'View\View.EntregasDia.pas' {view_EntregasDia},
  View.SuporteRemessa in 'View\View.SuporteRemessa.pas' {view_SuporteRemessa},
  FMX.CodeReader in 'C:\Componentes\TCodeReader\src\FMX.CodeReader.pas',
  CodeReader.DW.Camera in 'C:\Componentes\TCodeReader\src\CodeReader.DW.Camera.pas',
  CodeReader.DW.Android.Helpers in 'C:\Componentes\TCodeReader\src\CodeReader.DW.Android.Helpers.pas',
  CodeReader.DW.Androidapi.JNI.App in 'C:\Componentes\TCodeReader\src\CodeReader.DW.Androidapi.JNI.App.pas',
  CodeReader.DW.Androidapi.JNI.DWCameraHelpers in 'C:\Componentes\TCodeReader\src\CodeReader.DW.Androidapi.JNI.DWCameraHelpers.pas',
  CodeReader.DW.Androidapi.JNI.Hardware.Camera2 in 'C:\Componentes\TCodeReader\src\CodeReader.DW.Androidapi.JNI.Hardware.Camera2.pas',
  CodeReader.DW.Androidapi.JNI.SupportV4 in 'C:\Componentes\TCodeReader\src\CodeReader.DW.Androidapi.JNI.SupportV4.pas',
  CodeReader.DW.Androidapi.JNI.View in 'C:\Componentes\TCodeReader\src\CodeReader.DW.Androidapi.JNI.View.pas',
  CodeReader.DW.Camera.Android in 'C:\Componentes\TCodeReader\src\CodeReader.DW.Camera.Android.pas',
  CodeReader.DW.CameraPreview.Android in 'C:\Componentes\TCodeReader\src\CodeReader.DW.CameraPreview.Android.pas',
  CodeReader.DW.CameraPreview in 'C:\Componentes\TCodeReader\src\CodeReader.DW.CameraPreview.pas',
  CodeReader.DW.Consts.Android in 'C:\Componentes\TCodeReader\src\CodeReader.DW.Consts.Android.pas',
  CodeReader.DW.Consts in 'C:\Componentes\TCodeReader\src\CodeReader.DW.Consts.pas',
  CodeReader.DW.Messaging in 'C:\Componentes\TCodeReader\src\CodeReader.DW.Messaging.pas',
  CodeReader.DW.NativeImage.Android in 'C:\Componentes\TCodeReader\src\CodeReader.DW.NativeImage.Android.pas',
  CodeReader.DW.NativeImage in 'C:\Componentes\TCodeReader\src\CodeReader.DW.NativeImage.pas',
  CodeReader.DW.Permissions.Helpers in 'C:\Componentes\TCodeReader\src\CodeReader.DW.Permissions.Helpers.pas',
  CodeReader.DW.Types in 'C:\Componentes\TCodeReader\src\CodeReader.DW.Types.pas',
  CodeReader.DW.UIHelper.Android in 'C:\Componentes\TCodeReader\src\CodeReader.DW.UIHelper.Android.pas',
  CodeReader.DW.UIHelper in 'C:\Componentes\TCodeReader\src\CodeReader.DW.UIHelper.pas',
  CodeReader.ZXing.BarcodeFormat in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.BarcodeFormat.pas',
  CodeReader.ZXing.BaseLuminanceSource in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.BaseLuminanceSource.pas',
  CodeReader.ZXing.Binarizer in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.Binarizer.pas',
  CodeReader.ZXing.BinaryBitmap in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.BinaryBitmap.pas',
  CodeReader.ZXing.BitSource in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.BitSource.pas',
  CodeReader.ZXIng.ByteSegments in 'C:\Componentes\TCodeReader\src\CodeReader.ZXIng.ByteSegments.pas',
  CodeReader.ZXing.CharacterSetECI in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.CharacterSetECI.pas',
  CodeReader.ZXing.Common.BitArray in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.Common.BitArray.pas',
  CodeReader.ZXing.Common.BitArrayImplementation in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.Common.BitArrayImplementation.pas',
  CodeReader.ZXing.Common.BitMatrix in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.Common.BitMatrix.pas',
  CodeReader.ZXing.Common.Detector.MathUtils in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.Common.Detector.MathUtils.pas',
  CodeReader.ZXing.Common.Detector.WhiteRectangleDetector in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.Common.Detector.WhiteRectangleDetector.pas',
  CodeReader.ZXing.Common.DetectorResult in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.Common.DetectorResult.pas',
  CodeReader.ZXing.Common.GridSampler in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.Common.GridSampler.pas',
  CodeReader.ZXing.Common.PerspectiveTransform in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.Common.PerspectiveTransform.pas',
  CodeReader.ZXing.Common.ReedSolomon.GenericGF in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.Common.ReedSolomon.GenericGF.pas',
  CodeReader.ZXing.Common.ReedSolomon.ReedSolomonDecoder in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.Common.ReedSolomon.ReedSolomonDecoder.pas',
  CodeReader.ZXing.Datamatrix.DataMatrixReader in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.Datamatrix.DataMatrixReader.pas',
  CodeReader.ZXing.Datamatrix.Internal.BitMatrixParser in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.Datamatrix.Internal.BitMatrixParser.pas',
  CodeReader.ZXing.Datamatrix.Internal.DataBlock in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.Datamatrix.Internal.DataBlock.pas',
  CodeReader.ZXing.Datamatrix.Internal.DecodedBitStreamParser in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.Datamatrix.Internal.DecodedBitStreamParser.pas',
  CodeReader.ZXing.Datamatrix.Internal.Decoder in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.Datamatrix.Internal.Decoder.pas',
  CodeReader.ZXing.Datamatrix.Internal.Detector in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.Datamatrix.Internal.Detector.pas',
  CodeReader.ZXing.Datamatrix.Internal.Version in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.Datamatrix.Internal.Version.pas',
  CodeReader.ZXing.DecodeHintType in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.DecodeHintType.pas',
  CodeReader.ZXing.DecoderResult in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.DecoderResult.pas',
  CodeReader.ZXing.DefaultGridSampler in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.DefaultGridSampler.pas',
  CodeReader.ZXing.EncodeHintType in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.EncodeHintType.pas',
  CodeReader.ZXing.GlobalHistogramBinarizer in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.GlobalHistogramBinarizer.pas',
  CodeReader.ZXing.Helpers in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.Helpers.pas',
  CodeReader.ZXing.HybridBinarizer in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.HybridBinarizer.pas',
  CodeReader.ZXing.InvertedLuminanceSource in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.InvertedLuminanceSource.pas',
  CodeReader.ZXing.LuminanceSource in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.LuminanceSource.pas',
  CodeReader.ZXing.MultiFormatReader in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.MultiFormatReader.pas',
  CodeReader.ZXing.OneD.Code39Reader in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.OneD.Code39Reader.pas',
  CodeReader.ZXing.OneD.Code93Reader in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.OneD.Code93Reader.pas',
  CodeReader.ZXing.OneD.Code128Reader in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.OneD.Code128Reader.pas',
  CodeReader.ZXing.OneD.EAN8Reader in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.OneD.EAN8Reader.pas',
  CodeReader.ZXing.OneD.EAN13Reader in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.OneD.EAN13Reader.pas',
  CodeReader.ZXing.OneD.EANManufacturerOrgSupport in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.OneD.EANManufacturerOrgSupport.pas',
  CodeReader.ZXing.OneD.ITFReader in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.OneD.ITFReader.pas',
  CodeReader.ZXing.OneD.OneDReader in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.OneD.OneDReader.pas',
  CodeReader.ZXing.OneD.UPCAReader in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.OneD.UPCAReader.pas',
  CodeReader.ZXing.OneD.UPCEANExtension2Support in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.OneD.UPCEANExtension2Support.pas',
  CodeReader.ZXing.OneD.UPCEANExtension5Support in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.OneD.UPCEANExtension5Support.pas',
  CodeReader.ZXing.OneD.UPCEANExtensionSupport in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.OneD.UPCEANExtensionSupport.pas',
  CodeReader.ZXing.OneD.UPCEANReader in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.OneD.UPCEANReader.pas',
  CodeReader.ZXing.OneD.UPCEReader in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.OneD.UPCEReader.pas',
  CodeReader.ZXing.PlanarYUVLuminanceSource in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.PlanarYUVLuminanceSource.pas',
  CodeReader.ZXing.QrCode.Internal.AlignmentPattern in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.QrCode.Internal.AlignmentPattern.pas',
  CodeReader.ZXing.QrCode.Internal.AlignmentPatternFinder in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.QrCode.Internal.AlignmentPatternFinder.pas',
  CodeReader.ZXing.QrCode.Internal.AlignmentPatternImplementation in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.QrCode.Internal.AlignmentPatternImplementation.pas',
  CodeReader.ZXing.QrCode.Internal.BitMatrixParser in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.QrCode.Internal.BitMatrixParser.pas',
  CodeReader.ZXing.QrCode.Internal.DataBlock in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.QrCode.Internal.DataBlock.pas',
  CodeReader.ZXing.QrCode.Internal.DataMask in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.QrCode.Internal.DataMask.pas',
  CodeReader.ZXing.QrCode.Internal.DecodedBitStreamParser in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.QrCode.Internal.DecodedBitStreamParser.pas',
  CodeReader.ZXing.QrCode.Internal.Decoder in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.QrCode.Internal.Decoder.pas',
  CodeReader.ZXing.QrCode.Internal.Detector in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.QrCode.Internal.Detector.pas',
  CodeReader.ZXing.QrCode.Internal.ErrorCorrectionLevel in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.QrCode.Internal.ErrorCorrectionLevel.pas',
  CodeReader.ZXing.QrCode.Internal.FinderPattern in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.QrCode.Internal.FinderPattern.pas',
  CodeReader.ZXing.QrCode.Internal.FinderPatternFinder in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.QrCode.Internal.FinderPatternFinder.pas',
  CodeReader.ZXing.QrCode.Internal.FinderPatternImplementation in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.QrCode.Internal.FinderPatternImplementation.pas',
  CodeReader.ZXing.QrCode.Internal.FinderPatternInfo in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.QrCode.Internal.FinderPatternInfo.pas',
  CodeReader.ZXing.QrCode.Internal.FormatInformation in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.QrCode.Internal.FormatInformation.pas',
  CodeReader.ZXing.QrCode.Internal.Mode in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.QrCode.Internal.Mode.pas',
  CodeReader.ZXing.QrCode.Internal.QRCodeDecoderMetaData in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.QrCode.Internal.QRCodeDecoderMetaData.pas',
  CodeReader.ZXing.QrCode.Internal.Version in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.QrCode.Internal.Version.pas',
  CodeReader.ZXing.QrCode.QRCodeReader in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.QrCode.QRCodeReader.pas',
  CodeReader.ZXing.Reader in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.Reader.pas',
  CodeReader.ZXing.ReadResult in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.ReadResult.pas',
  CodeReader.ZXing.ResultMetadataType in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.ResultMetadataType.pas',
  CodeReader.ZXing.ResultPoint in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.ResultPoint.pas',
  CodeReader.ZXing.ResultPointImplementation in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.ResultPointImplementation.pas',
  CodeReader.ZXing.RGBLuminanceSource in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.RGBLuminanceSource.pas',
  CodeReader.ZXing.ScanManager in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.ScanManager.pas',
  CodeReader.ZXing.StringUtils in 'C:\Componentes\TCodeReader\src\CodeReader.ZXing.StringUtils.pas',
  Model.RESTBoletos in 'Model\Model.RESTBoletos.pas',
  Controller.RESTBoletos in 'Controller\Controller.RESTBoletos.pas',
  CodeReader.DW.Androidapi.JNI.Os in 'C:\Componentes\TCodeReader\src\CodeReader.DW.Androidapi.JNI.Os.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(Tview_Login, view_Login);
  Application.CreateForm(TDM_Main, DM_Main);
  Application.Run;
end.
